services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/docker/data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/docker/data/mosquitto/config:/mosquitto/config
      - /opt/docker/data/mosquitto/data:/mosquitto/data
      - /opt/docker/data/mosquitto/log:/mosquitto/log

  cherubini:
    build: ./cherubini
    container_name: cherubini
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/docker/data/cherubini/remote.json:/app/remote.json
    environment:
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - TX_PIN=23
    depends_on:
      - mosquitto

